# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches-ignore:
     -main

  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
       mysql database: 'gameshop' # Optional, default value is "test". The specified database which will be create
       mysql root password: 'brg76htq' # Required if "mysql user" is empty, default is empty. The root superuser password
       mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
       mysql password: 'brg76htq' # Required if "mysql user" exists. The password for the "mysql user"
     
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file Gameshop-BE/pom.xml
